---
name: Flotas de taxis
locale: es
type: practice
beta: false
teacher_info: |
  Guía tipo examen de diseño funcional

  Buenas! Debido al problema que existe con la llegada de Übar al país, el gobierno nos pidió que le demos una mano para controlar un poco más a las empresas de taxis.

  Ayudanos!
language: haskell
id_format: '%05d'
order:
- 1
